#cloud-config
apt_update: true

packages:
  - java-1.8.0-openjdk-headless
  - curl
  - screen
  - bash
  - grep

write_files:
  - path: /etc/systemd/system/minecraft@.service
    content: |
      [Unit]
      Description=Minecraft Server %i
      After=network.target

      [Service]
      WorkingDirectory=/opt/minecraft/%i
      PrivateUsers=true
      User=ec2-user
      Group=ec2-user
      ProtectSystem=full
      ProtectHome=true
      ProtectKernelTunables=true
      ProtectKernelModules=true
      ProtectControlGroups=true

      # --- Exec commands (executed inside WorkingDirectory)
      ExecStart=/bin/sh -c '/usr/bin/screen -DmS mc-%i /usr/bin/java -server -Xms512M -Xmx1G -XX:+UseG1GC -XX:+CMSIncrementalPacing -XX:+CMSClassUnloadingEnabled -XX:ParallelGCThreads=2 -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -jar $(ls -v | grep -i "FTBServer.*jar\|server.*jar" | head -n1) nogui'

      ExecReload=/usr/bin/screen -p 0 -S mc-%i -X eval 'stuff "reload"\\015'

      ExecStop=/usr/bin/screen -p 0 -S mc-%i -X eval 'stuff "say SERVER SHUTTING DOWN IN 15 SECONDS."\\015'
      ExecStop=/bin/sleep 15
      ExecStop=/usr/bin/screen -p 0 -S mc-%i -X eval 'stuff "say SERVER SHUTTING DOWN. Saving world..."\\015'
      ExecStop=/usr/bin/screen -p 0 -S mc-%i -X eval 'stuff "save-all"\\015'
      ExecStop=/usr/bin/screen -p 0 -S mc-%i -X eval 'stuff "stop"\\015'
      ExecStop=/bin/sync
      ExecStop=/bin/sleep 10 # Async wait to stop

      StandardOutput=syslog
      StandardError=syslog
      SyslogIdentifier=mc-%i

      Restart=on-failure
      RestartSec=60s

      [Install]
      WantedBy=multi-user.target
    owner: ec2-user:ec2-user
    permissions: '0750'

# TODO
# - enable minecraftd service (systemctl)
runcmd:
  - yum -y update
  - mkdir -p /opt/minecraft/server
  - aws s3 cp s3://${s3_bucket}/server /opt/minecraft/server --recursive
  - chown -R ec2-user:ec2-user /opt/minecraft
  - systemctl enable minecraft@server
  - systemctl start minecraft@server
